version: '3'

services:
  ACNHorizonsBotV2:
    build:
      context: ./ACNHorizonsBotV2
    container_name: ACNHorizonsBotV2
    image: ACNHorizonsBot:V2.0.0
    environment:
      - SECRETS_FOLDER_PATH: "./secrets"
      - API_URL: "${API_URL}"
      - TWITTER_API_KEY: "${TWITTER_API_KEY}"
      - TWITTER_API_SECRET: "${TWITTER_API_SECRET}"
      - TWITTER_ACCESS_TOKEN: "${TWITTER_ACCESS_TOKEN}"
      - TWITTER_ACCESS_SECRET: "${TWITTER_ACCESS_SECRET}"
